jdk:
  - oraclejdk11
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache components:
  - git submodule update --init --remote --recursive

before_install:
  - ./gradlew build pack
  
install: 
  - ./gradlew ciBuild
 
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

dist: xenial
addons:
  apt:
    sources:
      - docker-xenial
      
env:
  global:
    - SYSTEM_TESTS_HOME="test"
    - GIT_BRANCH=${TRAVIS_BRANCH}
    - DOCKER_HOST = "unix:///var/run/docker.sock"
