# CircleCI 2.1 configuration file
version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11
  build-tools: circleci/build-tools@2.2.0

executors:
  gradle:
    docker:
      - image: 'circleci/openjdk:11.0.2-jdk-stretch'

jobs:
  aion-checkout:
    executor: gradle
    steps:
      - checkout

workflows:
  aion-build-pack:
    jobs:
      - diagnostics:
          post-steps:
            - diagnostic-orb/store-report
          pre-steps:
            - diagnostic-orb/env-info
            - diagnostic-orb/memory        
      - gradle/run:
          requires:
            - diagnostics          
          command: build pack -x test
  aion-build-cibuild:
    jobs:
      - diagnostics:
          post-steps:
            - diagnostic-orb/store-report
          pre-steps:
            - diagnostic-orb/env-info
            - diagnostic-orb/memory        
      - gradle/run:
          requires:
            - diagnostics          
          command: ciBuild
