### aion.network Circle CI pipeline

version: 2.1

commands:
  git_setup:
    description: 'Commands needed to sync and update git and submodules'
    steps:
      - run:
          name: Git Submodule Sync
          command: git submodule sync
      - run:
          name: Git Submodule Update
          command: git submodule update --init

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    environment:
      TERM: dumb
      GIT_BRANCH: ${CIRCLE_BRANCH}
      DOCKER_HOST: 'unix:///var/run/docker.sock'
      SYSTEM_TESTS_HOME: test
      _JAVA_OPTIONS: "-Xms512m -Xmx4096m -XX:+UseContainerSupport"

    steps:
      # Check out the source repository
      - checkout

      # Sync and update submodules
      - git_setup

      # Create the build artifacts directory
      - run:
          name: Create build artifacts directory
          command: mkdir -p ~/pack

      # Create the build artifacts directory *** (temporary step until JAVA_HOME can be used)
      - run:
          name: Create the JDK directory
          command: sudo mkdir -p /usr/lib/jvm/jdk-11.0.1

      # Create symlink for current Java release *** (temporary step until JAVA_HOME can be used)
      - run:
          name: Create symlink for current Java release
          command: sudo ln -s  /usr/lib/jvm/jdk-11.0.1 /usr/lib/jvm/java-11-openjdk-amd64

      # Restore gradle dependency cache items (if possible)
      - restore_cache:
          keys: gradle-deps-v1-{{ .Branch }}-{{ checksum "build.gradle" }}

      # Run the gradle build and pack process
      - run:
          name: Perform SonarQube analysis on Gradle project
          command: ~/repo/gradlew --scan sonarqube \
            -Dsonar.projectKey=danaionnet_aion \
            -Dsonar.organization=danaionnet-github \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=ace9614c3cfe59d06153cbcd1b6577188355eeb1

      # Run the gradle build & pack processes
      - run:
          name: Building Gradle project (parallel mode)
          command: ~/repo/gradlew build pack --scan --build-cache --parallel

      # Save gradle dependency cache items
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-deps-v1-{{ .Branch }}-{{ checksum "build.gradle" }}

      # Store build artifacts (compressed files)
      - store_artifacts:
          path: ~/pack/aion-v*.tar.bz
          destination: build-output-archive

      # Run the gradle ciBuild test
      - run:
          name: Testing Gradle project
          command: ~/repo/gradlew ciBuild --scan --build-cache

      # Save test results
      - run:
          name: Saving test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      
      # Store test results
      - store_test_results:
          path: ~/test-results

      # Store test artifacts
      - store_artifacts:
          path: ~/test-results/junit         

workflows:
  build-and-test:
    jobs:
      - build

