# CircleCI 2.1 configuration file
version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11

executors:
  gradle:
    docker:
      - image: 'circleci/openjdk:11.0.2-jdk-stretch'

jobs:
  aion-checkout:
    executor: gradle
    steps:
      - checkout

workflows:
  aion-build-pack:
    jobs:
      - gradle/run:
          command: build pack -x test
  aion-build-cibuild:
    jobs:
      - gradle/run:
          command: ciBuild
