### aion.network Circle CI pipeline

version: 2.1

commands:
  git_setup:
    description: 'Commands needed to sync and update git and submodules'
    steps:
      - run:
          name: Git Submodule Sync
          command: git submodule sync
      - run:
          name: Git Submodule Update
          command: git submodule update --init

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch
    environment:
      TERM: dumb
      GIT_BRANCH: ${CIRCLE_BRANCH}
      DOCKER_HOST: 'unix:///var/run/docker.sock'
      SYSTEM_TESTS_HOME: test
      _JAVA_OPTIONS: "-Xms1g"

    steps:
      # Check out the source repository
      - checkout

      # Sync and update submodules
      - git_setup

      # Create the build artifacts directory
      - run:
          name: Create build artifacts directory
          command: mkdir -p ~/pack

      # Create symlink for current Java release *** (temporary step until JAVA_HOME can be used)
      - run:
          name: Create symlink for current Java release
          command: sudo ln -s -f -T /usr/lib/jvm/java-11-openjdk-amd64/ /usr/lib/jvm/jdk-11.0.1

      # Restore gradle dependency cache items (if possible)
      - restore_cache:
          keys: 
            - gradle-deps-v1-{{ .Branch }}-{{ checksum "~/repo/build.gradle" }}

      # Run the gradle build & pack processes (Parallel Mode)
      - run:
          name: Building Gradle project
          command: ~/repo/gradlew build pack --scan --build-cache --parallel

      # Store build artifacts (compressed files)
      - store_artifacts:
          path: ~/pack/aion-v*.tar.gz
          destination: build-output-archive

      # Run the gradle ciBuild test
      - run:
          name: Testing Gradle project
          command: ~/repo/gradlew ciBuild --scan --build-cache --parallel

      # Save gradle dependency cache items
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-deps-v1-{{ .Branch }}-{{ checksum "~/repo/build.gradle" }}

      # Save test results
      - run:
          name: Saving test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      
      # Store test results
      - store_test_results:
          path: ~/test-results

      # Store test artifacts
      - store_artifacts:
          path: ~/test-results/junit         

workflows:
  build-and-test:
    jobs:
      - build

